#!/bin/bash


# Script to provide human readable system information
# Dependencies: sudo, resolvectl, lshw, lspci
# Variables START

myHostName="$(hostname)"

# Date formatted Wed June 03 / hh:mm:ss AM/PM
currentDateTime="$(date +"%a %B %d / %r")"

# Grab just the pretty name from the source file
# runs it in a sub shell to not dirty up the variables

myPrettyOS="$(source /etc/os-release; echo $PRETTY_NAME)"

# Use the pretty format to cleanly grab uptime number, and text (days, months hours etc.)
uptime="$(uptime -p | awk '{print $2 " " $3}')"

# Grab CPU using lshw filter with cpu. 
# grep finds product: and stops at first result (incase multicpu)
# sed replaces "any amount of white space" before and after "product:"
cpuName="$(lshw -c cpu 2>/dev/null| grep -m1 "product:" | sed 's/[[:space:]]*product:[[:space:]]*//')"

# Using 2 greps to first grab the correct section as -c memory grabs cache/firmware. 
# This method works on both VM and Arch where info on banks is available as well.
# Issues with correct ram size on Arch when using non sudo. Sudo version needs additional filtering to remove other memory sections.
ramInstalled="$(sudo lshw -c memory 2>/dev/null | grep -A5 -i "system memory" | grep -m1 "size:" | sed 's/[[:space:]]*size:[[:space:]]*//')"

# Same situation here. Grep the VGA line and strip the leading text out.
videoCard="$(lspci | grep -i vga | sed 's/.*VGA compatible controller: //')"

# lsblk with no headings (-n), -o MODEL, SIZE (columns), exclude (-e) 7 which is loop's major number
# -d to exclude partitions / slaves
# $'\n' at the start/end to newline to have a clean visual of the disks, human readable
myDisks=$'\n'"$(lsblk -d -e 7 -n -o MODEL,SIZE| sed 's/^/\t/')"$'\n'

# Default Route with ip route. $5 is the dev. 
# Assuming IPV4 not IPV6
interface="$(ip -4 route show default | awk '{print $5}')"
defaultGateway="$(ip -4 route show default | awk '{print $3}')"
wanIP="$(ip a show dev $interface | grep -w "inet" | awk '{print $2}')"


dnsIP="$(resolvectl status | grep -w "Current DNS Server:" | awk '{print $4}')"
# Varaibles END


# Template for output to Terminal. 

cat << EOF 

System Report for $myHostName generated by $USER, on $currentDateTime
 
System Information
------------------
OS: $myPrettyOS
Uptime: $uptime
CPU: $cpuName
RAM: $ramInstalled
Disk(s): $myDisks
Video: $videoCard
Host Address: $wanIP
Gateway IP: $defaultGateway
DNS Server: $dnsIP
 
System Status
-------------
Users Logged In: USER,USER,USER...
Disk Space: FREE SPACE FOR LOCAL FILESYSTEMS IN FORMAT: /MOUNTPOINT N
Process Count: N
Load Averages: N, N, N
Listening Network Ports: N, N, N, ...
UFW Status: UFWSTATUS

EOF
