#!/bin/bash


# Script to provide human readable system information
# SED Searches use [[:space:]] in lieu of space
# Dependencies: sudo, lshw, lspci, systemd (resolvctl, loginctl)
# Potential Todo: Create functions for repeated seds



# Variables START

myHostName="$(hostname)"

# Date formatted Wed June 03 / hh:mm:ss AM/PM
currentDateTime="$(date +"%a %B %d / %r")"

# Grab just the pretty name from the source file
# runs it in a sub shell to not dirty up the variables

myPrettyOS="$(source /etc/os-release; echo $PRETTY_NAME)"

# Used the -p flag so it catches, 1 day, 5:10 minutes
uptime="$(uptime -p | sed 's/^up[[:space:]]//')"

# Grab CPU using lshw filter with cpu. 
# grep finds product: and stops at first result (incase multicpu)
# sed replaces "any amount of white space" before and after "product:"
cpuName="$(lshw -c cpu 2>/dev/null| grep -m1 "product:" | sed 's/[[:space:]]*product:[[:space:]]*//')"

# Using 2 greps to first grab the correct section as -c memory grabs cache/firmware. 
# This method works on both VM and Arch where info on banks is available as well.
# Issues with correct ram size on Arch when using non sudo. Sudo version needs additional filtering to remove other memory sections.
ramInstalled="$(sudo lshw -c memory 2>/dev/null | grep -A5 -i "system memory" | grep -m1 "size:" | sed 's/[[:space:]]*size:[[:space:]]*//')"

# Same situation here. Grep the VGA line and strip the leading text out.
videoCard="$(lspci | grep -i vga | sed 's/.*VGA compatible controller:[[:space:]]//')"

# lsblk with no headings (-n), -o MODEL, SIZE (columns), exclude (-e) 7 which is loop's major number
# -d to exclude partitions / slaves
# $'\n' at the start/end to newline to have a clean visual of the disks, human readable
myDisks=$'\n'"$(lsblk -d -e 7 -n -o MODEL,SIZE| sed 's/^/\t/')"$'\n'

# Default Route with ip route. $5 is the dev. 
# Assuming IPV4 not IPV6
interface="$(ip -4 route show default | awk '{print $5}')"
defaultGateway="$(ip -4 route show default | awk '{print $3}')"
wanIP="$(ip a show dev $interface | grep -w "inet" | awk '{print $2}')"


dnsIP="$(resolvectl status | grep -w "Current DNS Server:" | awk '{print $4}')"



# List users with no legends, print $2 but thats newline, replace newlines with , and replace the last comma with newline.

# Test for login CTL, suppress stdout and redirect stderr to stdout
if which loginctl > /dev/null  2>&1
    then
        # Loginctl if its available. Who wasnt working, unsure if w will catch users, but systemd should be more consistent
        loggedInUsers="$(loginctl list-users --no-legend | awk '{print $2}' | tr '\n' ',' | sed 's/,$/\n/')"
    else
        # W version of the same thing. W should be more unversal than loginctl, but loginctl is preferred.
        # -s short makes users first arg, same replace as the login ctl one above. 
        loggedInUsers="$(w -h -s | awk '{print $1}' | tr '\n' ',' | sed 's/,$/\n/')"
fi


# ps -e for all, then count the lines. Dont need to use -o pid.
procCount="$(ps -e --no-headers | wc -l)"

# uptime has load averages
# replace everything up to and including "load average: "

loadInfo="$(uptime | sed 's/.*load average:[[:space:]]//')"

# ss no headers, tcp, udp, listening, numbers (no resolve to things like dns)
# $5 = ip:port combo
# remove everything before the port
# sort and show only uniques. Each port is in new lines, need to strip again but this format requires spaces
# TR alone doesnt work here as its 1:1, use sed to turn , into ,. Needs switch g for all matches.
# Note [[:space:]] does not work in replacements, only in search. Thre is a space in the replacement global

listeningPorts="$(ss -Htuln | awk '{print $5}' | sed 's/.*://' | sort -u | tr '\n' "," | sed 's/,$/\n/; s/,/, /g')"

# UFW status, requires sudo, and strip the leading status
# UFW Status on Arch shows additional output, grab just the status
ufwStatus="$(sudo ufw status | grep -w "Status:" | sed 's/.*:[[:space:]]//')"

# Varaibles END


# Template for output to Terminal. 

cat << EOF 

System Report for $myHostName generated by $USER, on $currentDateTime
 
System Information
------------------
OS: $myPrettyOS
Uptime: $uptime
CPU: $cpuName
RAM: $ramInstalled
Disk(s): $myDisks
Video: $videoCard
Host Address: $wanIP
Gateway IP: $defaultGateway
DNS Server: $dnsIP
 
System Status
-------------
Users Logged In: $loggedInUsers
Disk Space: FREE SPACE FOR LOCAL FILESYSTEMS IN FORMAT: /MOUNTPOINT N
Process Count: $procCount
Load Averages: $loadInfo
Listening Network Ports: $listeningPorts
UFW Status: $ufwStatus

EOF